<a href="https://colab.research.google.com/github/aymenhmid/NLP_Guide/blob/main/TensorFlow/TF_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow Basic Operations

## Introduction
This notebook covers basic operations in TensorFlow, including:
- Tensor creation (constants, variables)
- Mathematical operations
- Matrix multiplication
- Using placeholders (legacy TF1) vs eager execution (TF2)
- Automatic differentiation with `tf.GradientTape`

## Installation
!pip install tensorflow

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


##Basic Tensors

In [2]:
## Constants
# Create scalar
scalar = tf.constant(7)
print("Scalar:", scalar.numpy())

# Create vector
vector = tf.constant([10, 10])
print("Vector:", vector.numpy())

# Create matrix
matrix = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
print("Matrix:\n", matrix.numpy())

# Create 3D tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=tf.int32)
print("3D Tensor:\n", tensor_3d.numpy())
#################################################################################
## Variable
# Create variable
variable = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
print("Variable:\n", variable.numpy())

# Modify variable
variable.assign([[5.0, 6.0], [7.0, 8.0]])
print("Modified Variable:\n", variable.numpy())

Scalar: 7
Vector: [10 10]
Matrix:
 [[1. 2.]
 [3. 4.]]
3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Variable:
 [[1. 2.]
 [3. 4.]]
Modified Variable:
 [[5. 6.]
 [7. 8.]]


##Basic Operations

In [3]:
a = tf.constant(5)
b = tf.constant(3)

# Arithmetic operations
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print(f"Add: {add.numpy()}, Sub: {sub.numpy()}, Mul: {mul.numpy()}, Div: {div.numpy()}")

Add: 8, Sub: 2, Mul: 15, Div: 1.6666666666666667


In [4]:
## MAtrix Multiplication
a = tf.constant(5)
b = tf.constant(3)

# Arithmetic operations
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print(f"Add: {add.numpy()}, Sub: {sub.numpy()}, Mul: {mul.numpy()}, Div: {div.numpy()}")

Add: 8, Sub: 2, Mul: 15, Div: 1.6666666666666667


## Eager Execution vs Graph Mode (Legacy)

In [5]:
##TF2 Eager Execution (Default)
# Operations run immediately
x = tf.constant(3)
y = tf.constant(5)
print("Eager execution result:", (x + y).numpy())

Eager execution result: 8


In [6]:
##Legacy TF1 Placeholder/Session (for reference)
# Only needed for legacy code
import tensorflow.compat.v1 as tf1
tf1.disable_eager_execution()

# Create placeholder
ph = tf1.placeholder(tf.int32, shape=(2,))
a = tf1.constant([5, 3])
result = a + ph

# Run in session
with tf1.Session() as sess:
    print("TF1 session result:", sess.run(result, feed_dict={ph: [2, 4]}))

TF1 session result: [7 7]


In [7]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


### Automatic Differentiation

In [13]:
tf.config.run_functions_eagerly(True)

# Enable eager execution (TF2 does this by default)
# Define a scalar variable
x = tf.Variable(3.0)

# Record operations for automatic differentiation
with tf.GradientTape() as tape:
    y = x**2  # y = x^2

# Compute dy/dx
dy_dx = tape.gradient(y, x)


with tf.compat.v1.Session() as sess: # Create a TensorFlow session
    sess.run(tf.compat.v1.global_variables_initializer()) # Initialize variables
    x_val, y_val, dy_dx_val = sess.run([x, y, dy_dx]) # Evaluate the tensors
    print(f"x = {x_val}, y = x^2 = {y_val}, dy/dx = {dy_dx_val}")

x = 3.0, y = x^2 = 9.0, dy/dx = 6.0


### Tensor and Numpy Interoperability

In [18]:
import tensorflow as tf

@tf.function
def run():
    tensor = tf.constant([1, 2, 3])
    tf.print("Tensor to NumPy:", tensor)

    # NumPy to Tensor
    new_tensor = tf.constant([10, 20, 30])
    tf.print("NumPy to Tensor:", new_tensor)

run()

